[CmdletBinding()]
param(
  [string]$BaseBranch = "main",
  [switch]$DoPush,
  [switch]$DoCreateOrUpdatePr
)

$ErrorActionPreference = "Stop"

function Step([string]$Message) {
  Write-Host ""
  Write-Host "==> $Message" -ForegroundColor Cyan
}

function Require-CleanWorktree {
  $status = git status --porcelain
  if ($LASTEXITCODE -ne 0) {
    throw "git status failed."
  }
  if ($status) {
    throw "Working tree is not clean. Commit or stash changes first."
  }
}

function Require-Command([string]$Name) {
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  return $null -ne $cmd
}

if ($PSCommandPath) {
  $scriptRoot = Split-Path -Parent $PSCommandPath
} else {
  $scriptRoot = (Get-Location).Path
}

Set-Location $scriptRoot

$branch = git rev-parse --abbrev-ref HEAD
if ($LASTEXITCODE -ne 0) {
  throw "Unable to determine current git branch."
}

$commit = git rev-parse --short HEAD
if ($LASTEXITCODE -ne 0) {
  throw "Unable to determine current commit."
}

$prTitle = "MCP-03 bootstrap verification and evidence refresh"
$outDir = Join-Path $scriptRoot "out\pr"
$prBodyPath = Join-Path $outDir "mcp03-pr-body.md"
$bootstrapScript = Join-Path $scriptRoot "scripts\build-mcp03-evidence.ps1"

Step "Checking working tree"
Require-CleanWorktree

Step "Locating bootstrap script"
if (-not (Test-Path $bootstrapScript)) {
  throw "Bootstrap script not found: $bootstrapScript"
}

Step "Running bootstrap verification"
& powershell -ExecutionPolicy Bypass -File $bootstrapScript
if ($LASTEXITCODE -ne 0) {
  throw "build-mcp03-evidence.ps1 failed."
}

Step "Building PR body"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$lines = @(
  "## Summary",
  "",
  "- Refresh MCP-03 bootstrap and verification flow.",
  "- Re-run static analysis, unit, replay, property, and formal smoke checks.",
  "- Regenerate evidence artifacts for review.",
  "",
  "## Verification",
  "",
  "- bootstrap script: ``scripts/build-mcp03-evidence.ps1``",
  "- branch: ``$branch``",
  "- commit: ``$commit``",
  "",
  "## Notes",
  "",
  "- PR body generated by ``pr-mcp03.ps1``.",
  "- Evidence artifacts should be available under ``artifacts/``."
)

Set-Content -Path $prBodyPath -Value $lines -Encoding UTF8

Write-Host ""
Write-Host "PR body written to: $prBodyPath" -ForegroundColor Green

if ($DoPush) {
  Step "Pushing branch"
  git push -u origin $branch
  if ($LASTEXITCODE -ne 0) {
    throw "git push failed."
  }
} else {
  Write-Host ""
  Write-Host "Skipping push. Re-run with -DoPush to publish the branch."
}

if ($DoCreateOrUpdatePr) {
  Step "Creating or updating PR"

  if (-not (Require-Command "gh")) {
    Write-Host ""
    Write-Host "GitHub CLI not found; PR body is ready." -ForegroundColor Yellow
    Write-Host "Create the PR manually with:"
    Write-Host "  base: $BaseBranch"
    Write-Host "  head: $branch"
    Write-Host "  title: $prTitle"
    Write-Host "  body file: $prBodyPath"
  } else {
    $existingPr = gh pr list --head $branch --base $BaseBranch --json number --jq ".[0].number"
    if ($LASTEXITCODE -ne 0) {
      throw "Unable to query existing PRs with gh."
    }

    if ($existingPr) {
      gh pr edit $existingPr --title $prTitle --body-file $prBodyPath
      if ($LASTEXITCODE -ne 0) {
        throw "gh pr edit failed."
      }
    } else {
      gh pr create --base $BaseBranch --head $branch --title $prTitle --body-file $prBodyPath
      if ($LASTEXITCODE -ne 0) {
        throw "gh pr create failed."
      }
    }
  }
} else {
  Write-Host ""
  Write-Host "Skipping PR creation. Re-run with -DoCreateOrUpdatePr to use gh."
}

Write-Host ""
Write-Host "Final branch status:"
git status --short

Write-Host ""
Write-Host "Done." -ForegroundColor Green
