from pathlib import Path
import shutil, time, re

p = Path("s43.py")
bak = Path(f"s43.py.bak_fix_deep_prune_ghost_orders_{int(time.time())}")
shutil.copy2(p, bak)

lines = p.read_text(encoding="utf-8").splitlines()

start = None
end = None

for i, line in enumerate(lines):
    if line.startswith("    async def deep_prune_ghost_orders("):
        start = i
        break

if start is None:
    raise SystemExit("ERROR: deep_prune_ghost_orders start not found")

# Find next class-level method after this one.
for j in range(start + 1, len(lines)):
    if (
        lines[j].startswith("    async def ")
        or lines[j].startswith("    def ")
    ):
        end = j
        break

if end is None:
    raise SystemExit("ERROR: next method boundary after deep_prune_ghost_orders not found")

replacement = [
    "    async def deep_prune_ghost_orders(self, positions: Optional[Dict[str, 'Position']] = None, *, force: bool = False) -> int:",
    "        \"\"\"Aggressive ghost/orphan order pruning, written defensively.",
    "",
    "        This implementation is intentionally conservative: it only attempts",
    "        to cancel orders that look bot-owned by CID/prefix or are known in",
    "        the local order journal. All exchange/journal failures are swallowed",
    "        so this maintenance task never breaks the main trading loop.",
    "        \"\"\"",
    "        now = float(time.time())",
    "        positions = positions or {}",
    "",
    "        try:",
    "            interval = float(_env_float(\"DEEP_PRUNE_INTERVAL_SEC\", 600.0) or 600.0)",
    "        except Exception:",
    "            interval = 600.0",
    "",
    "        if (not force) and (now - float(getattr(self, \"_last_deep_prune_ts\", 0.0) or 0.0)) < interval:",
    "            return 0",
    "",
    "        self._last_deep_prune_ts = now",
    "",
    "        if bool(getattr(self.cfg, \"dry_run\", False)):",
    "            self.ghost_order_count = 0",
    "            return 0",
    "",
    "        if not isinstance(getattr(self, \"_ghost_seen\", None), dict):",
    "            setattr(self, \"_ghost_seen\", {})",
    "",
    "        ghost_seen: Dict[str, dict] = getattr(self, \"_ghost_seen\", {}) or {}",
    "",
    "        # Load persisted ghost state once.",
    "        if not bool(getattr(self, \"_ghost_state_loaded\", False)):",
    "            try:",
    "                base = str(getattr(self.cfg, \"state_path\", \"\") or \"\").strip()",
    "                if base:",
    "                    path = f\"{base}.{str(self._wallet or 'W1')}.ghost.json\"",
    "                else:",
    "                    path = f\"ghost_orders_{str(self._wallet or 'W1')}.json\"",
    "                setattr(self, \"_ghost_state_path\", path)",
    "",
    "                if os.path.isfile(path):",
    "                    with open(path, \"r\", encoding=\"utf-8\") as f:",
    "                        obj = json.load(f)",
    "                    if isinstance(obj, dict) and isinstance(obj.get(\"orders\"), dict):",
    "                        ghost_seen.update(dict(obj.get(\"orders\") or {}))",
    "            except Exception:",
    "                pass",
    "            try:",
    "                setattr(self, \"_ghost_state_loaded\", True)",
    "            except Exception:",
    "                pass",
    "",
    "        known_oids: set = set()",
    "        known_cids: set = set()",
    "",
    "        # Collect pending journal IDs/CIDs.",
    "        try:",
    "            if self._oj is not None:",
    "                pend = self._oj.pending() or {}",
    "                for _cid, rec in (pend or {}).items():",
    "                    if _cid:",
    "                        known_cids.add(str(_cid))",
    "                    if not isinstance(rec, dict):",
    "                        continue",
    "                    oid = rec.get(\"exchange_order_id\") or rec.get(\"order_id\") or rec.get(\"id\")",
    "                    if oid:",
    "                        known_oids.add(str(oid))",
    "        except Exception:",
    "            pass",
    "",
    "        # Fetch open orders defensively.",
    "        resps = []",
    "        try:",
    "            for st in (\"open\", \"new\", \"active\"):",
    "                try:",
    "                    r = await self._ex.list_orders(status=st)",
    "                    if r is not None:",
    "                        resps.append(r)",
    "                except Exception:",
    "                    pass",
    "",
    "            if not resps:",
    "                try:",
    "                    r = await self._ex.list_orders()",
    "                    if r is not None:",
    "                        resps.append(r)",
    "                except Exception:",
    "                    pass",
    "        except Exception:",
    "            resps = []",
    "",
    "        orders: List[dict] = []",
    "        try:",
    "            for r in (resps or []):",
    "                try:",
    "                    extracted = OrderJournal._extract_orders(r)",
    "                except Exception:",
    "                    extracted = r if isinstance(r, list) else []",
    "                for o in (extracted or []):",
    "                    if isinstance(o, dict):",
    "                        orders.append(o)",
    "        except Exception:",
    "            orders = []",
    "",
    "        # Deduplicate by exchange order id when possible.",
    "        seen = set()",
    "        uniq: List[dict] = []",
    "        for o in (orders or []):",
    "            if not isinstance(o, dict):",
    "                continue",
    "            try:",
    "                oid0 = OrderJournal._order_id(o)",
    "            except Exception:",
    "                oid0 = o.get(\"order_id\") or o.get(\"id\")",
    "            k = str(oid0 or \"\").strip()",
    "            if not k:",
    "                k = str(id(o))",
    "            if k in seen:",
    "                continue",
    "            seen.add(k)",
    "            uniq.append(o)",
    "        orders = uniq",
    "",
    "        try:",
    "            prefixes = tuple(",
    "                x.strip()",
    "                for x in str(os.getenv(\"BOT_CID_PREFIXES\", \"raz_,sov_,bot_\") or \"raz_,sov_,bot_\").split(\",\")",
    "                if x.strip()",
    "            )",
    "        except Exception:",
    "            prefixes = (\"raz_\", \"sov_\", \"bot_\")",
    "",
    "        try:",
    "            max_cancel = int(_env_int(\"DEEP_PRUNE_MAX_CANCEL\", 7) or 7)",
    "        except Exception:",
    "            max_cancel = 7",
    "",
    "        cancelled = 0",
    "        ghost_count = 0",
    "",
    "        for o in (orders or []):",
    "            if not isinstance(o, dict):",
    "                continue",
    "",
    "            try:",
    "                oid = OrderJournal._order_id(o)",
    "            except Exception:",
    "                oid = o.get(\"order_id\") or o.get(\"id\")",
    "",
    "            try:",
    "                cid = OrderJournal._client_id(o)",
    "            except Exception:",
    "                cid = (",
    "                    o.get(\"cid\")",
    "                    or o.get(\"client_id\")",
    "                    or o.get(\"clientId\")",
    "                    or o.get(\"client_order_id\")",
    "                    or o.get(\"clientOrderId\")",
    "                )",
    "",
    "            oid_s = str(oid or \"\").strip()",
    "            cid_s = str(cid or \"\").strip()",
    "",
    "            if not oid_s and not cid_s:",
    "                continue",
    "",
    "            bot_owned = False",
    "            if cid_s and cid_s in known_cids:",
    "                bot_owned = True",
    "            if oid_s and oid_s in known_oids:",
    "                bot_owned = True",
    "            if cid_s and any(cid_s.startswith(pref) for pref in prefixes):",
    "                bot_owned = True",
    "",
    "            if not bot_owned:",
    "                continue",
    "",
    "            ghost_count += 1",
    "            key = oid_s or cid_s",
    "            rec = ghost_seen.get(key) if isinstance(ghost_seen.get(key), dict) else {}",
    "            if not rec:",
    "                rec = {\"first_seen\": now}",
    "            rec[\"last_seen\"] = now",
    "            rec[\"cid\"] = cid_s",
    "            rec[\"oid\"] = oid_s",
    "            ghost_seen[key] = rec",
    "",
    "            if cancelled >= max_cancel:",
    "                continue",
    "",
    "            try:",
    "                if oid_s:",
    "                    await self._ex.cancel_order(oid_s)",
    "                elif cid_s:",
    "                    await self._ex.cancel_order(cid_s)",
    "                cancelled += 1",
    "                try:",
    "                    self._logger.warning(",
    "                        \"event=DEEP_PRUNE_CANCEL wallet=%s oid=%s cid=%s\",",
    "                        self._wallet,",
    "                        oid_s,",
    "                        cid_s,",
    "                    )",
    "                except Exception:",
    "                    pass",
    "            except Exception:",
    "                pass",
    "",
    "        self.ghost_order_count = int(ghost_count)",
    "",
    "        # Persist ghost state best-effort.",
    "        try:",
    "            path = str(getattr(self, \"_ghost_state_path\", \"\") or \"\")",
    "            if path:",
    "                with open(path, \"w\", encoding=\"utf-8\") as f:",
    "                    json.dump({\"ts\": now, \"orders\": ghost_seen}, f, ensure_ascii=False)",
    "        except Exception:",
    "            pass",
    "",
    "        return int(cancelled)",
]

lines[start:end] = replacement

p.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"patched deep_prune_ghost_orders: lines {start+1}..{end}; backup={bak}")
