# scripts/Write-AtomicJson.ps1
<#
.SYNOPSIS
    Atomic JSON write with durability guarantees (Phase B.1)
.DESCRIPTION
    Writes JSON data atomically with validation, preventing corruption
    on system crash or power loss.
.PARAMETER Path
    Target JSON file path
.PARAMETER Data
    Pre-formatted JSON string (UTF-8 LF, canonical)
.NOTES
    Phase: B.1 (Durability - Atomic Write)
    Generated by: roadmap Phase B implementation
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$Path,
    
    [Parameter(Mandatory = $true)]
    [string]$Data
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$tempPath = "$Path.tmp"

try {
    # 1. Write to temp file (UTF-8 no BOM, LF only)
    [System.IO.File]::WriteAllText(
        $tempPath,
        $Data,
        [System.Text.UTF8Encoding]::new($false)
    )
    
    # 2. Validate: parse JSON to ensure well-formed
    $null = Get-Content -Raw -Path $tempPath | ConvertFrom-Json
    
    # 3. Atomic rename (OS-level atomic operation on NTFS)
    Move-Item -Path $tempPath -Destination $Path -Force
    
} catch {
    # 4. Cleanup temp file on any failure
    if (Test-Path $tempPath) {
        Remove-Item -Path $tempPath -Force -ErrorAction SilentlyContinue
    }
    
    throw "Atomic write failed for ${Path}: $_"
}
