from pathlib import Path
import shutil, time

p = Path("s43.py")
bak = Path(f"s43.py.bak_fix_place_limit_retry_loop_{int(time.time())}")
shutil.copy2(p, bak)

lines = p.read_text(encoding="utf-8").splitlines()

start = None
end = None

for i, line in enumerate(lines):
    if line.strip() == "last_exc: Optional[Exception] = None":
        start = i
        break

if start is None:
    raise SystemExit("ERROR: retry-loop start boundary not found")

for j in range(start + 1, min(len(lines), start + 220)):
    if line := lines[j]:
        if line.startswith("    async def place_ladder("):
            end = j
            break

if end is None:
    raise SystemExit("ERROR: place_ladder boundary not found")

replacement = [
    "        last_exc: Optional[Exception] = None",
    "",
    "        for attempt in range(self.max_retries + 1):",
    "            try:",
    "                async with self._submit_lock:",
    "                    if attempt == 0:",
    "                        order_key = f\"{str(side).lower()}_{px2}_{qty2}_{sym}\"",
    "                        if (",
    "                            getattr(self, \"_last_order_key\", None) == order_key",
    "                            and (time.time() - float(getattr(self, \"_last_order_time\", 0.0) or 0.0)) < 5.0",
    "                        ):",
    "                            try:",
    "                                self._logger.warning(\"Duplicate order prevented for %s\", sym)",
    "                            except Exception:",
    "                                pass",
    "",
    "                            if self._oj is not None:",
    "                                try:",
    "                                    self._oj.mark_resolved(",
    "                                        cid,",
    "                                        final_state=\"SKIPPED_DUP\",",
    "                                        note=str(order_key)",
    "                                    )",
    "                                except Exception:",
    "                                    pass",
    "",
    "                            return {",
    "                                \"ok\": False,",
    "                                \"skipped\": True,",
    "                                \"reason\": \"DUPLICATE_PREVENTED\",",
    "                                \"cid\": cid,",
    "                            }",
    "",
    "                        self._last_order_key = order_key",
    "                        self._last_order_time = time.time()",
    "",
    "                    order_kwargs = dict(kwargs)",
    "                    order_kwargs.pop(\"cid\", None)",
    "                    order_kwargs.setdefault(\"notional_irt\", float(notional_irt))",
    "                    order_kwargs.setdefault(\"fill_type\", \"limit\")",
    "                    order_kwargs.setdefault(\"market\", \"spot\")",
    "                    order_kwargs.setdefault(",
    "                        \"reduce_only\",",
    "                        str(side or \"\").lower().startswith(\"sell\")",
    "                    )",
    "",
    "                    resp = await self._ex.place_order(",
    "                        sym,",
    "                        side,",
    "                        float(qty2),",
    "                        float(px2),",
    "                        cid=cid,",
    "                        **order_kwargs",
    "                    )",
    "",
    "                if resp is None:",
    "                    raise ApiError(\"Order submission returned None\")",
    "",
    "                ok = False",
    "                try:",
    "                    ok = bool(resp.get(\"ok\")) or int(float(resp.get(\"status\") or resp.get(\"code\") or 0)) in (200, 201)",
    "                except Exception:",
    "                    ok = bool(isinstance(resp, dict) and resp.get(\"ok\"))",
    "",
    "                if ok:",
    "                    oid = \"\"",
    "                    try:",
    "                        oid = str(resp.get(\"order_id\") or resp.get(\"id\") or \"\") if isinstance(resp, dict) else \"\"",
    "                    except Exception:",
    "                        oid = \"\"",
    "",
    "                    if self._oj is not None:",
    "                        try:",
    "                            self._oj.mark_ack(cid, exchange_order_id=oid, raw=resp)",
    "                        except Exception:",
    "                            pass",
    "",
    "                    if self._rec:",
    "                        try:",
    "                            self._rec.record_order(",
    "                                time.time(),",
    "                                self._wallet,",
    "                                sym,",
    "                                side,",
    "                                float(qty2),",
    "                                float(px2),",
    "                                float(notional_irt),",
    "                                ok=True,",
    "                                order_id=oid,",
    "                                raw=resp,",
    "                            )",
    "                        except Exception:",
    "                            pass",
    "",
    "                    try:",
    "                        if isinstance(resp, dict) and cid:",
    "                            if (",
    "                                \"cid\" not in resp",
    "                                and \"client_id\" not in resp",
    "                                and \"clientId\" not in resp",
    "                                and \"client_order_id\" not in resp",
    "                                and \"clientOrderId\" not in resp",
    "                            ):",
    "                                resp = dict(resp)",
    "                                resp[\"cid\"] = str(cid)",
    "                    except Exception:",
    "                        pass",
    "",
    "                    return resp",
    "",
    "                if self._oj is not None:",
    "                    try:",
    "                        self._oj.mark_resolved(",
    "                            cid,",
    "                            final_state=\"REJECTED\",",
    "                            note=str(resp)[:300],",
    "                        )",
    "                    except Exception:",
    "                        pass",
    "",
    "                try:",
    "                    if isinstance(resp, dict) and cid:",
    "                        if (",
    "                            \"cid\" not in resp",
    "                            and \"client_id\" not in resp",
    "                            and \"clientId\" not in resp",
    "                            and \"client_order_id\" not in resp",
    "                            and \"clientOrderId\" not in resp",
    "                        ):",
    "                            resp = dict(resp)",
    "                            resp[\"cid\"] = str(cid)",
    "                except Exception:",
    "                    pass",
    "",
    "                return resp",
    "",
    "            except (TradingHalt, TemporaryPause):",
    "                raise",
    "",
    "            except asyncio.TimeoutError as e:",
    "                last_exc = e",
    "                try:",
    "                    self._logger.error(",
    "                        \"event=ORDER_TIMEOUT wallet=%s sym=%s cid=%s\",",
    "                        self._wallet,",
    "                        sym,",
    "                        cid,",
    "                    )",
    "                except Exception:",
    "                    pass",
    "",
    "                if attempt < self.max_retries:",
    "                    try:",
    "                        await asyncio.sleep(float(self.base_backoff) * (2 ** attempt))",
    "                    except Exception:",
    "                        pass",
    "                    continue",
    "                break",
    "",
    "            except Exception as e:",
    "                last_exc = e",
    "                try:",
    "                    self._logger.error(",
    "                        \"event=ORDER_POST_FAIL side=%s sym=%s cid=%s attempt=%d/%d err=%s\",",
    "                        side,",
    "                        sym,",
    "                        cid,",
    "                        attempt + 1,",
    "                        self.max_retries + 1,",
    "                        e,",
    "                        exc_info=True,",
    "                    )",
    "                except Exception:",
    "                    pass",
    "",
    "                if attempt < self.max_retries:",
    "                    try:",
    "                        await asyncio.sleep(float(self.base_backoff) * (2 ** attempt))",
    "                    except Exception:",
    "                        pass",
    "                    continue",
    "                break",
    "",
    "        if self._rec:",
    "            try:",
    "                self._rec.record_order(",
    "                    time.time(),",
    "                    self._wallet,",
    "                    sym,",
    "                    side,",
    "                    float(qty2),",
    "                    float(px2),",
    "                    float(notional_irt),",
    "                    ok=False,",
    "                    order_id=None,",
    "                    raw={\"error\": str(last_exc), \"cid\": cid},",
    "                )",
    "            except Exception:",
    "                pass",
    "",
    "        if self._oj is not None:",
    "            try:",
    "                self._oj.mark_uncertain(cid, err=str(last_exc))",
    "            except Exception:",
    "                pass",
    "",
    "        transient = isinstance(last_exc, (asyncio.TimeoutError, OSError))",
    "        try:",
    "            if aiohttp is not None and isinstance(last_exc, aiohttp.ClientError):",
    "                transient = True",
    "        except Exception:",
    "            pass",
    "",
    "        if transient and (not self.cfg.dry_run):",
    "            try:",
    "                _phase54_audit_log(\"raise_TradingHalt\", line=11515)",
    "            except Exception:",
    "                pass",
    "            raise TradingHalt(f\"ORDER_DESYNC cid={cid} side={side} sym={sym}\") from last_exc",
    "",
    "        raise ApiError(f\"Order failed after retries: {last_exc}\")",
]

lines[start:end] = replacement

p.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"patched place_limit retry loop: lines {start+1}..{end}; backup={bak}")
