#!/data/data/com.termux/files/usr/bin/bash
set -e

echo "== S43 Repository Hardening Patch =="

if [ ! -f "s43.py" ]; then
  echo "ERROR: s43.py not found. Run this patch from the project root."
  exit 1
fi

mkdir -p docs logs simulation tests release_backups tools_archive archive_packed_backup

echo "[1/6] Writing .gitignore..."
cat > .gitignore <<'GITIGNORE'
# Python
__pycache__/
*.pyc
*.pyo
*.pyd
*.pdb

# Virtual environments / env files
venv/
.venv/
env/
.env
.env.*
!.env.example

# Logs
logs/
*.log

# Temporary files
tmp/
temp/
*.tmp
*.bak
*.old
*.swp

# Archives and packed backups
archive/
archive_packed_backup/
*.tar.gz
*.zip
*.rar
*.7z

# Snapshots / historical backups
snapshots/
*_snapshot_*
*_backup_*
*.before_*

# Reports / audit artifacts
reports/
audit_reports/
*_audit_*
*_report_*
*_status_*

# Termux / system / OS
.termux/
.DS_Store
Thumbs.db

# Local editor files
.vscode/
.idea/
GITIGNORE

echo "[2/6] Writing docs/PROJECT_STRUCTURE.md..."
cat > docs/PROJECT_STRUCTURE.md <<'PROJECT_STRUCTURE'
# S43 Project Structure

This document describes the expected structure of the S43 project.

## Core Files

`s43.py`

Main production source file.

## Release Backups

`release_backups/`

Contains immutable release copies and release manifests.

Expected examples:
```text
s43.py.final_YYYYMMDD_HHMMSS
S43_RELEASE_MANIFEST_YYYYMMDD_HHMMSS.txt

## Tools Archive

`tools_archive/`

Contains engineering utilities that were used for cleanup, audit, review, or extraction.

These tools are archived for reproducibility and should not be required for normal runtime.

## Packed Archive Backup

`archive_packed_backup/`

Contains compressed historical archives and their manifests.

Expected examples:

text
S43_ARCHIVE_PACK_YYYYMMDD_HHMMSS.tar.gz
S43_ARCHIVE_PACK_MANIFEST_YYYYMMDD_HHMMSS.txt
archive_original_YYYYMMDD_HHMMSS/

## Logs

`logs/`

Runtime logs generated by the application.

## Simulation

`simulation/`

Simulation scripts and experimental runtime checks.

## Tests

`tests/`

Unit tests, integration tests, and verification scripts.

## Docs

`docs/`

Project documentation, operational guides, and recovery instructions.
PROJECT_STRUCTURE

echo "[3/6] Writing docs/RUNBOOK.md..."
cat > docs/RUNBOOK.md <<'RUNBOOK'
# S43 Runbook

Operational guide for running and verifying the S43 system.

## Requirements

Recommended Python version:

bash
python --version

Python 3.10+ is recommended.

## Start

Run:

bash
python s43.py

## Compile Check

Before and after changes, run:

bash
python -m py_compile s43.py

Expected result:

No output and exit code `0`.

## Release Integrity Check

Find the latest release backup:

bash
ls -t release_backups/s43.py.final_* | head -n 1

Compare active file with latest release backup:

bash
latest_release="$(ls -t release_backups/s43.py.final_* | head -n 1)"
cmp -s s43.py "$latest_release" && echo "OK: active s43.py matches latest release backup" || echo "WARNING: active s43.py differs from latest release backup"

## Logs

Runtime logs should be stored in:

text
logs/

## Emergency Stop

Press:

text
CTRL+C

## Basic Health Check

Confirm:

- `s43.py` compiles cleanly
- runtime starts without immediate exception
- logs are updating if logging is enabled
- latest release backup exists
RUNBOOK

echo "[4/6] Writing docs/DISASTER_RECOVERY.md..."
cat > docs/DISASTER_RECOVERY.md <<'DISASTER_RECOVERY'
# S43 Disaster Recovery Guide

This document describes how to recover the S43 project from common failure scenarios.

## Scenario 1: Active `s43.py` Is Corrupted

List available release backups:

bash
ls -lt release_backups/s43.py.final_*

Restore the latest release:

bash
latest_release="$(ls -t release_backups/s43.py.final_* | head -n 1)"
cp "$latest_release" s43.py
python -m py_compile s43.py

Verify:

bash
cmp -s s43.py "$latest_release" && echo "OK: restored file matches release backup"

## Scenario 2: Project Artifacts Need Recovery

Go to packed archive directory:

bash
cd archive_packed_backup

List available packs:

bash
ls -lh S43_ARCHIVE_PACK_*.tar.gz

Verify archive listing:

bash
tar -tzf S43_ARCHIVE_PACK_YYYYMMDD_HHMMSS.tar.gz >/dev/null && echo "OK: archive is readable"

Extract:

bash
tar -xzf S43_ARCHIVE_PACK_YYYYMMDD_HHMMSS.tar.gz

## Scenario 3: Runtime Failure

Stop the process with `CTRL+C`, then run:

bash
python -m py_compile s43.py
python s43.py

Check logs:

bash
ls -lt logs/

## Backup Priority

Primary production source:

text
s43.py

Primary release backups:

text
release_backups/

Historical packed archives:

text
archive_packed_backup/

Recommended external backup target:

text
external storage or cloud backup
DISASTER_RECOVERY

echo "[5/6] Writing s43_backup_rotate.sh..."
cat > s43_backup_rotate.sh <<'ROTATE'
#!/data/data/com.termux/files/usr/bin/bash
set -e

BACKUP_DIR="release_backups"
MAX_BACKUPS="${MAX_BACKUPS:-10}"

echo "== S43 Backup Rotation =="

if [ ! -d "$BACKUP_DIR" ]; then
  echo "ERROR: $BACKUP_DIR not found."
  exit 1
fi

count="$(find "$BACKUP_DIR" -maxdepth 1 -type f -name 's43.py.final_*' | wc -l | tr -d ' ')"

echo "Found release backups: $count"
echo "Max backups to keep: $MAX_BACKUPS"

if [ "$count" -gt "$MAX_BACKUPS" ]; then
  remove_count=$((count - MAX_BACKUPS))
  echo "Removing old backups: $remove_count"

  find "$BACKUP_DIR" -maxdepth 1 -type f -name 's43.py.final_*' -printf '%T@ %p\n' \
| sort -nr \
| tail -n "$remove_count" \
| cut -d' ' -f2- \
| while IFS= read -r file; do
rm -f "$file"
echo "Removed: $file"
done
else
  echo "No rotation needed."
fi

echo "Backup rotation complete."
ROTATE

chmod +x s43_backup_rotate.sh

echo "[6/6] Verification..."

python -m py_compile s43.py
echo "OK: s43.py compile passed"

if ls release_backups/s43.py.final_* >/dev/null 2>&1; then
  latest_release="$(ls -t release_backups/s43.py.final_* | head -n 1)"
  if cmp -s s43.py "$latest_release"; then
echo "OK: active s43.py matches latest release backup"
  else
echo "WARNING: active s43.py differs from latest release backup"
  fi
else
  echo "WARNING: no release backup found in release_backups/"
fi

echo ""
echo "== Hardening Files Created =="
ls -lh .gitignore s43_backup_rotate.sh docs/PROJECT_STRUCTURE.md docs/RUNBOOK.md docs/DISASTER_RECOVERY.md

echo ""
echo "== S43 Repository Hardening Complete =="
